//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RETMINSISTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BODEGA()
        {
            this.KARDEX = new HashSet<KARDEX>();
        }
    
        public short ID_BODEGA { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string COD_BODEGA { get; set; }
        public string UBICACION { get; set; }
        public string DESCRIPCION_BODEGA { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARDEX> KARDEX { get; set; }
    }
}
