//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RETMINSISTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCRIPCION_KARDEX
    {
        public int ID_DESCRIPCION_KARDEX { get; set; }
        public int ID_USUARIO { get; set; }
        public string COD_KARDEX { get; set; }
        public System.DateTime FECHA_KARDEX { get; set; }
        public string DESCRIPCION_KARDEX1 { get; set; }
        public string TIPO_TRANSACION { get; set; }
        public double VALOR_UNITARIO { get; set; }
        public double CANTIDAD { get; set; }
        public double VALOR { get; set; }
        public Nullable<double> CANTIDAD_SALDO { get; set; }
        public Nullable<double> VALOR_SALDO { get; set; }
        public Nullable<System.DateTime> CADUCIDAD { get; set; }
    
        public virtual KARDEX KARDEX { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
