//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RETMINSISTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.KARDEX = new HashSet<KARDEX>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string COD_PROOVEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public string APELLIDO_PROVEEDOR { get; set; }
        public string EMPRESA_REPRESENTA { get; set; }
        public string CONTACTO { get; set; }
        public string CORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARDEX> KARDEX { get; set; }
    }
}
